# NginX related configs
---
  - block:
    - name: "Coping the config file"
      copy:
        src: "files/{{ item.0 }}"
        dest: "{{ nginx_conf_server_location }}"
      with_together:
        - [ '{{ nginx_http_file }}', '{{ nginx_https_file }}' ]

    - name: "ReStart nginx"
      command: service nginx restart

    become: true
    become_method: sudo
    become_user: root